---
label: Config
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
- type: list
  name: disableLanguages
  label: disableLanguages
- type: text
  name: disqusShortname
  label: disqusShortname
- type: text
  name: paginate
  label: paginate
- type: text
  name: summaryLength
  label: summaryLength
- type: text
  name: theme
  label: theme
- type: text
  name: title
  label: title
- type: field_group
  name: Languages
  label: Languages
  fields:
  - type: field_group
    name: en
    label: en
    fields:
    - type: text
      name: contentDir
      label: contentDir
    - type: text
      name: copyright
      label: copyright
    - type: textarea
      name: footer_content
      label: footer_content
    - type: text
      name: home
      label: home
    - type: text
      name: languageCode
      label: languageCode
    - type: text
      name: languageName
      label: languageName
    - type: number
      name: weight
      label: weight
  - type: field_group
    name: fr
    label: fr
    fields:
    - type: text
      name: contentDir
      label: contentDir
    - type: text
      name: copyright
      label: copyright
    - type: textarea
      name: footer_content
      label: footer_content
    - type: text
      name: home
      label: home
    - type: text
      name: languageCode
      label: languageCode
    - type: text
      name: languageName
      label: languageName
    - type: number
      name: weight
      label: weight
- type: field_group
  name: menu
  label: menu
  fields:
  - type: field_group_list
    name: footer
    label: footer
    fields:
    - type: text
      name: URL
      label: URL
    - type: text
      name: name
      label: name
    - type: number
      name: weight
      label: weight
  - type: field_group_list
    name: main
    label: main
    fields:
    - type: text
      name: URL
      label: URL
    - type: text
      name: name
      label: name
    - type: number
      name: weight
      label: weight
- type: field_group
  name: outputs
  label: outputs
  fields:
  - type: list
    name: home
    label: home
- type: field_group
  name: params
  label: params
  fields:
  - type: text
    name: address
    label: address
  - type: text
    name: author
    label: author
  - type: text
    name: contact_form_action
    label: contact_form_action
  - type: text
    name: description
    label: description
  - type: text
    name: email
    label: email
  - type: text
    name: google_analitycs_id
    label: google_analitycs_id
  - type: file
    name: logo
    label: logo
  - type: file
    name: logo_footer
    label: logo_footer
  - type: text
    name: mobile
    label: mobile
  - type: boolean
    name: quick_contact
    label: quick_contact
  - type: boolean
    name: search
    label: search
  - type: boolean
    name: top_header
    label: top_header
  - type: field_group
    name: map
    label: map
    fields:
    - type: boolean
      name: enable
      label: enable
    - type: text
      name: gmap_api
      label: gmap_api
    - type: text
      name: map_latitude
      label: map_latitude
    - type: text
      name: map_longitude
      label: map_longitude
    - type: file
      name: map_marker
      label: map_marker
  - type: field_group
    name: navigation_button
    label: navigation_button
    fields:
    - type: boolean
      name: enable
      label: enable
    - type: text
      name: label
      label: label
    - type: text
      name: link
      label: link
  - type: field_group
    name: plugins
    label: plugins
    fields:
    - type: field_group_list
      name: css
      label: css
      fields:
      - type: text
        name: link
        label: link
    - type: field_group_list
      name: js
      label: js
      fields:
      - type: text
        name: link
        label: link
  - type: field_group
    name: preloader
    label: preloader
    fields:
    - type: boolean
      name: enable
      label: enable
    - type: text
      name: preloader
      label: preloader
  - type: field_group
    name: subscription
    label: subscription
    fields:
    - type: boolean
      name: enable
      label: enable
    - type: text
      name: mailchimp_form_action
      label: mailchimp_form_action
    - type: text
      name: mailchimp_form_name
      label: mailchimp_form_name
  - type: field_group_list
    name: social
    label: social
    fields:
    - type: text
      name: icon
      label: icon
    - type: text
      name: URL
      label: URL
